//
//  AppDelegate.swift
//  TodayAir
//
//  Created by ows on 2015. 9. 23..
//  Copyright © 2015년 ESKompany. All rights reserved.
//

import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?


    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        
        let stations = [
            Station(name: "반송로", address:"경남 창원시 의창구 두대동145번지 시설관리공단 내 실내수영장 앞(원이대로 480)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "사파동", address:"경남 창원시 성산구 사파동(창이대로 706길)106-1(16-23)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "경화동", address:"경남 창원시 진해구 경화동242(경화로 16번길)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "하동읍", address:"경남 하동군 하동읍 읍내리180-3번지 하동군청 옥상 (군청로 23)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동상동", address:"경남 김해시 동상동(호계로 517번길 8)856", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "삼방동", address:"경남 김해시 삼방동200번지 (신어초등학교)(활천로 303)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "장유동", address:"경남 김해시 삼문동능동로 149 (장유건강지원센터 건물 옥상) (능동로 149)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "저구리", address:"경남 거제시 남부면 저구리산 116번지", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "아주동", address:"경남 거제시 아주동337-26 아주보건지소 (아주로 3길 25)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "사천읍", address:"경남 사천시 사천읍읍내로 52 사천읍사무소 (평화리 29)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대산면", address:"경남 창원시 의창구 대산면 갈전리816번지 대산정수장 내 송수펌프실 옥상", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "북부동", address:"경남 양산시 북부동331-2 (양산시 보건소)(북안남 5길 15)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "웅상읍", address:"경남 양산시 웅상읍 삼호리783-10 번지 (웅상노인복지회관) (삼호 9길 11)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "화산리", address:"울산 울주군 온산읍 화산리22", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "상남리", address:"울산 울주군 청량면 상남리(신석하 3길)595-7(5 청량면사무소 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "농소동", address:"울산 북구 호계동(호계7길)726번지 농소중학교(13)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "삼남면", address:"울산 울주군 삼남면 교동리(서향교 1길)1605-1(67-12) 울주군보건소 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "남상면", address:"경남 거창군 남상면 무촌리632-2 남상면사무소 내 복지회관 2층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "서석동", address:"광주 동구 서석동 31(서남로 1) 동구청보건소", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "농성동", address:"광주 서구 농성동329-1(농성1동 동사무소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "치평동", address:"광주 서구 치평동1242", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "두암동", address:"광주 북구 두암2동825-13(두암보건지소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "운암동", address:"광주 북구 운암동99(프린스호텔)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "건국동", address:"광주 북구 대촌동958-3(광주테크노파크 벤처지원센터 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "송정1동", address:"광주 광산구 송정1동(광산로)756-1(70) (송정1동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "오선동", address:"광주 광산구 오선동(하남산단 6번로)271 (107)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "주월동", address:"광주 남구 주월동(회서로 21번가길)493-13(13)(주월1동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "중앙동(전주)", address:"전북 전주시 완산구 중앙동32번지 중앙동주민센터 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "용당동", address:"전남 목포시 용당2동1053(용당2동 주민센터 2층옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "부흥동", address:"전남 목포시 옥암동1022(부흥동주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "광무동", address:"전남 여수시 광무동42-4(여수시민회관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "월내동", address:"전남 여수시 월내동1392 (여수산단 월내 패수종말처리장)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "문수동", address:"전남 여수시 문수동  161-5문수동주민센터 옥상", items:"SO2, CO, O3, PM10", type:"도시대기"),
            Station(name: "여천동(여수)", address:"전남 여수시 선원동704(여천동주민센터 부지내)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "덕충동", address:"전남 여수시 덕충안길 95만덕동주민자치센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "장천동", address:"전남 순천시 장천동53-1(순천시청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "연향동", address:"전남 순천시 연향동1379-1번지 순천시 연향도서관 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "순천만", address:"전남 순천시 대대동162-2 순천만 자연생태관 3층(갈대밭길 15)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "호두리", address:"전남 순천시 해룡면 호두리276-9 호두정수장 내", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "중동", address:"전남 광양시 중동1312-3(광양소방서)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "태인동", address:"전남 광양시 태인동1653-4(태인폐수처리장 사무실)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "진상면", address:"전남 광양시 진상면 섬거리292 (진상면사무소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "광양읍", address:"전남 광양시 광양읍 칠성리70번지", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "나불리", address:"전남 영암군 삼호면 나불리338-3 영암소방서 3층", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "송단리", address:"전남 화순군 북면 송단리338번지", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "이도동", address:"제주 제주시 이도2동1176-1(제주시청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "연동", address:"제주 제주시 연동322-1 번지 제주특별자치도청 제2청사 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동홍동", address:"제주 서귀포시 동홍동453-1(서귀포소방서)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "고산리", address:"제주 제주시 한경면 고산리3768", items:"SO2, CO, O3, NO2, PM10", type:"국가배경농도"),
            Station(name: "남산동", address:"대구 중구 남산동937-1 (헌혈의집 앞)(달구벌대로 2088)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "중구", address:"서울 중구 서소문동시청별관 제3동 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "한강대로", address:"서울 용산구 동자동43-207", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "종로구", address:"서울 종로구 효제동173-2(종로5,6가 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "청계천", address:"서울 중구 주교동125-1 (청계천4가 로타리 포인트다운 앞)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "종로", address:"서울 종로구 종로4가32-8 종묘공원 앞 도로변 인도", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "용산구", address:"서울 용산구 한남동726-336 한남직업전문학교 내", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "광진구", address:"서울 광진구 광나루로 571구의아리수정수센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "성동구", address:"서울 성동구 성수1가2동685-20 서울숲", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "강변북로", address:"서울 성동구 성수동1가  687-9한강사업본부 내 강변북로 옆", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "중랑구", address:"서울 중랑구 면목동62-2 건강가정지원센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동대문구", address:"서울 동대문구 용두2동237-1 용두초등학교", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동대문", address:"서울 중구 을지로7가135-5 (동대문운동장역4거리 인도)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "청량리", address:"서울 동대문구 청량리동746", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "성북구", address:"서울 성북구 길음3동1064-1(길음동 주민센터 3층옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "내부순환로", address:"서울 성북구 정릉3동998", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "도봉구", address:"서울 도봉구 쌍문동산80-1 청소년문화의 집", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "은평구", address:"서울 은평구 진흥로 215", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "서대문구", address:"서울 서대문구 연희동산 5-58 서대문구 자연사박물관", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "마포구", address:"서울 마포구 대흥동30-3 마포아트센터 5층", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "신촌로", address:"서울 마포구 노고산동31-6(신촌로타리 한일은행앞)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "강서구", address:"서울 강서구 화곡동1019-1 청소년 도서관", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "공항대로", address:"서울 강서구 가양1동530-4외 3필지", items:"SO2, CO, O3, PM10", type:"도로변대기"),
            Station(name: "구로구", address:"서울 구로구 구로동가마산로 27길 45(구로고등학교)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "영등포구", address:"서울 영등포구 당산동3가250번지(당산1동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "영등포로", address:"서울 영등포구 영등포동4가66", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "동작구", address:"서울 동작구 사당4동300-8(사당4동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동작대로 중앙차로", address:"서울 동작구 사당동739(4호 이수역 인근 도로중앙)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "관악구", address:"서울 관악구 신림5동1439-3 신림5동 주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "강남구", address:"서울 강남구 대치동1024-3 (국민은행 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "서초구", address:"서울 서초구 반포2동355(반포 2동 주민센터 3층 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "도산대로", address:"서울 강남구 논현동1", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "강남대로", address:"서울 서초구 양재1동  19-14서초구민회관 앞 버스중앙승강장의 안전지대", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "송파구", address:"서울 송파구 방이동88 올림픽 공원내", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "강동구", address:"서울 강동구 천호1동76-2 천호1동 주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "길동", address:"서울 강동구 길동426-1 길동사거리 강동성모병원 앞 인도", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "금천구", address:"서울 금천구 시흥5동832-14(시흥5동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "강북구", address:"서울 강북구 번1동417-11 번1동 주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "양천구", address:"서울 양천구 신정4동957-9(신정4동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "노원구", address:"서울 노원구 상계2동389-483(상계2동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "화랑로", address:"서울 노원구 공릉동 687-9태능입구역 8번출구 뒤 인도", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "신풍동", address:"경기 수원시 팔달구 신풍동123-69(선경도서관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "인계동", address:"경기 수원시 팔달구 인계동1111(수원시청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "광교동", address:"경기 수원시 영통구 법조로129(하동 981, 이의중학교 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "영통동", address:"경기 수원시 팔달구 영통동977-3", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "천천동", address:"경기 수원시 장안구 천천동300(성대 제2공학관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동수원", address:"경기 수원시 팔달구 우만동562-7번지 동수원 4거리 SK생명앞", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "고색동", address:"경기 수원시 권선구 고색동886-70", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "백현동", address:"경기 성남시 분당구 백현동651-3", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "단대동", address:"경기 성남시 수정구 단대동4888-2(단대동 복지회관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "정자1동", address:"경기 성남시 분당구 정자1동147번지 (정자1동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "수내동", address:"경기 성남시 분당구 수내동1(분당구청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "모란역", address:"경기 성남시 수정구 수진2동453번지 모란역 4거리 모란전광판 앞", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "복정동", address:"경기 성남시 수정구 복정동515번지 (상수도사업소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "운중동", address:"경기 성남시 분당구 운중동935 운중동 주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "상대원1동", address:"경기 성남시 중원구 상대원동1451", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "의정부동", address:"경기 의정부시 의정부2동551-2(경기도 도로관리사업소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "의정부1동", address:"경기 의정부시 의정부1동225-1 의정부1동 주민센터 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "안양6동", address:"경기 안양시 만안구 안양6동437-4 안양6동  주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "부림동", address:"경기 안양시 동안구 부림동1590(안양시청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "호계동", address:"경기 안양시 동안구 호계2동933-18(호계2동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "안양2동", address:"경기 안양시 만안구 안양2동842-2번지 안양2동 주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "철산동", address:"경기 광명시 철산동384(광명시 농협중앙회)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "소하동", address:"경기 광명시 소하동1291번지 소하1동 주민센타 및 광명시 노인복지회관 복합건물 옥상(6층)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "고잔동", address:"경기 안산시 단원구 고잔동515(수도권대기환경청 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "원시동", address:"경기 안산시 단원구산단로 112(민주노총 사무실)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "본오동", address:"경기 안산시 상록구 본오2동796-4(본오2동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "원곡동", address:"경기 안산시 단원구 원곡2동936-5(원곡2동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "부곡동1", address:"경기 안산시 상록구 부곡동671(부곡동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대부동", address:"경기 안산시 단원구 대부북동467 (대부출장소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "호수동", address:"경기 안산시 단원구 고잔(호수)동781-2", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "중앙로1", address:"경기 안산시 단원구 고잔1동554-1", items:"SO2, CO, NO2, PM10", type:"도로변대기"),
            Station(name: "별양동", address:"경기 과천시 별양동16번지 (문원초등학교)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "과천동", address:"경기 과천시 과천동249 (환경사업소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "교문동", address:"경기 구리시 교문동3-2(구리시 체육관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동구동", address:"경기 구리시 인창동56-36(노인아동복지회관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "부곡3동", address:"경기 의왕시 부곡3동166-24(부곡동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "고천동", address:"경기 의왕시 고천동272-2(고천동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "정왕동", address:"경기 시흥시 정왕동1799-5 (환경관리센터옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "시화공단", address:"경기 시흥시 정왕동 시화공단시화공단 2다 401(시화지원센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대야동", address:"경기 시흥시 대야동491-3(대야동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "금곡동", address:"경기 남양주시 금곡동185-10(남양주시청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "오남읍", address:"경기 남양주시 오남읍 양지리96-10 오남읍사무소", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "비전동", address:"경기 평택시 비전동846(평택시청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "안중", address:"경기 평택시 안중읍 안중리안중읍사무소 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "평택항", address:"경기 평택시 포승읍 만호리(포승읍 평택항로)576-4(184번길 38)한국산업단지공단 평택지사 본관 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "금촌동", address:"경기 파주시 금촌동953-1 (금촌2동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "행신동", address:"경기 고양시 덕양구 행신동924(행신배수지)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "식사동", address:"경기 고양시 일산동구 식사동위시티로 151", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "마두역", address:"경기 고양시 일산구 장항2동888", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "경안동", address:"경기 광주시 경안동53-4 농협중앙회 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "김량장동", address:"경기 용인시 김량장동286", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "수지", address:"경기 용인시 풍덕천동(수지)701-1 풍덕천1동 주민센터 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "기흥", address:"경기 용인시 기흥구 구갈동335번지 기흥구청 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "구갈동", address:"경기 용인시 기흥구 구갈동505-3", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "설성면", address:"경기 이천시 설성면 신필리산 88-5(전파연구소 입구)", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "창전동", address:"경기 이천시 창전동105-3", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "관인면", address:"경기 포천시 관인면사정리 140", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "선단동", address:"경기 포천시 선단동629-1", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "사우동", address:"경기 김포시 사우동236-2", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "고촌면", address:"경기 김포시 고촌면신곡리 530-1(고촌면사무소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "통진읍", address:"경기 김포시 통진면 마송리111-27(통진면사무소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "당동", address:"경기 군포시 당동752-10 (군포도서관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "산본동", address:"경기 군포시 금정동844(여성회관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "오산동", address:"경기 오산시 오산동48-2(오산시보건소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "신장동", address:"경기 하남시 신장2동520(하남시청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "남양동", address:"경기 화성시 남양동1340", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "향남", address:"경기 화성시 향남면 행정리287-1 (향남면사무소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동탄동", address:"경기 화성시 반송동 137동탄2동 주민센터 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "백석읍", address:"경기 양주시 백석읍꿈나무로 199", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "보산동", address:"경기 동두천시 싸리말로28(보산동 314-5) 보산동주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "봉산동", address:"경기 안성시 봉산동안성시청 식당동 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "여주시", address:"경기 여주시 하동131-11(중앙동사무소 2층 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "연천", address:"경기 연천군 연천읍 차탄리290-1", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "가평읍", address:"경기 가평군 가평읍석봉로 181(가평군청 의회동 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "양평", address:"경기 양평군 용문면 다문리343 용문도서관 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "중앙로", address:"강원 춘천시 중앙로 3가67-1(춘천시보건소 3층 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "석사동", address:"강원 춘천시 석사동322-1(석사119안전센터 2층 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "방산면", address:"강원 양구군 방산면 송현1리519-2번지 방산배수지 내", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "광복동", address:"부산 중구 광복동1가 9 (광복로 55번길 10)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "초량동", address:"부산 동구 중앙대로349번길(->중앙대로로 넘어가는길)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "태종대", address:"부산 영도구 동삼2동산29-1번지 태종대유원지관리사무소(전망로24)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "전포동", address:"부산 부산진구 전포동(전포대로 175번길 22)849-10 경남공고", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "온천동", address:"부산 동래구 온천2동(중앙대로)동래지하철 건너편(1335번길 24)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "명장동", address:"부산 동래구 명장동133-5 명장1동 주민센터(명장로 32)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대연동", address:"부산 남구 대연동918-1(수영로 196번길 80)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "학장동", address:"부산 사상구 학장동대동로 413 학장초등학교 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "덕천동", address:"부산 북구 덕천동365-1(만덕대로 155번길 81)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "청룡동", address:"부산 금정구 청룡동31-14 청룡노포동 주민센터 옥상(청룡로25)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "좌동", address:"부산 해운대구 좌1동1458-2번지 (좌1동 주민센터 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "장림동", address:"부산 사하구 장림동1140(161번길 2)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대저동", address:"부산 강서구 대저1동(낙동북로)1619 (236)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "녹산동", address:"부산 강서구 송정동(주) 삼성전기 부산사업장(녹산산업중로 333)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "연산동", address:"부산 연제구 연산5동1300 (중앙대로 1065번길 14)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "기장읍", address:"부산 기장군 기장읍 동부리320번지(읍내로 69)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "용수리", address:"부산 기장군 정관면 용수리(용수로4)141번지 정관면주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "수정동", address:"부산 동구 수정2동806-74 동구청(구청로1)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "부곡동", address:"부산 금정구 부곡로 156번길 7부곡 2동 주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "광안동", address:"부산 수영구 광안동(호암로)4동 주민센터 (9번길 34)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대신동", address:"부산 서구 동대신동대영로 73번길 92", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "회원동", address:"경남 창원시 마산회원구 회원1동52-11(회원1동 주민센터) (회원동11길 7)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "봉암동", address:"경남 창원시 마산회원구 봉암동472-10 봉암동 주민센터 (봉양로 148)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대송동", address:"울산 동구 대송동(대송5길)148-2 (10)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "성남동", address:"울산 중구 성남동219-137(만남의 거리 14) 성남119안전센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "부곡동2", address:"울산 남구 부곡동12125-2 (처용로 260-37)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "여천동(울산)", address:"울산 남구 여천동(납도로)250번지 (90)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "야음동", address:"울산 남구 야음동 (수암로)789-12번지(170) 야음중학교", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "삼산동", address:"울산 남구 삼산동1513-13 삼산동 주민센터 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "신정2동", address:"울산 남구 신정2동(문수로)1674(436 공업로타리)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "신정동", address:"울산 남구 신정동(봉월로)1210-9(20번길)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "덕신리", address:"울산 울주군 온산읍 덕신리(명봉거남로)36-4(2)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "무거동", address:"울산 남구 무거동(대학로)1522-2 (147번길 38)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "효문동", address:"울산 북구 효문동616-8(효문펌프장내)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "상봉동", address:"경남 진주시 상봉동858-17(상봉동 주민센터)(비봉로 85번길 12)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대안동", address:"경남 진주시 대안동(진주대로 1052)11-10", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "상대동", address:"경남 진주시 상대동33-85 (동진로 279)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "명서동", address:"경남 창원시 의창구 명서동111번지(명서2동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "웅남동", address:"경남 창원시 성산구 웅남동43-1(효성에바라) (공단로 303)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "가음정동", address:"경남 창원시 성산구 가음정동LG전자창원1공장 391-2(LG전자)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "용지동", address:"경남 창원시 의창구 용지동62-1번지 용지동 주민센터 3층 옥상 (용지로 239번길 19-4)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "부안군", address:"전북 부안군 부안읍 수정길 9-8부안군 수도사업소 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "수창동", address:"대구 중구 수창동73 (수창초등학교)(달성로 22길 30)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "지산동", address:"대구 수성구 지산동761-11(한국환경공단) (무학로 209)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "율하동", address:"대구 동구 율하동254-1 (안일초등학교)(율하동로 23길 66)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "이현동", address:"대구 서구 이현동48-60 (중리초등학교)(국채보상로 135)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "평리동", address:"대구 서구 평리3동730-1 (대평중학교내) (통학로 217)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "대명동", address:"대구 남구 대명동 3050 (성명초등학교)대구광역시 남구 성당로30길 55", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "노원동", address:"대구 북구 노원동3가 262번지(삼영초등학교)(3공단로 14길 31)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "신암동", address:"대구 동구 신암동72-1 (신암5동사무소)(아양로 37길 92)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "태전동", address:"대구 북구 태전동1076-5 (태암초등학교)(칠곡중앙대로 52길 56)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "만촌동", address:"대구 수성구 만촌2동934 (동원초등학교)(국채보상로 1000)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "호림동", address:"대구 달서구 성서공단로 11길 32대구기계부품연구원 1동 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "현풍면", address:"대구 달성군 현풍면부리 247 (상수도사업본부 달성사업소)(현풍중앙로 144-34)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "장흥동", address:"경북 포항시 남구 장흥동140-3(동일산업)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "죽도동", address:"경북 포항시 북구 죽도2동74-1(죽도2동주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대도동", address:"경북 포항시 남구 대도동111-6(상대2동주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대송면", address:"경북 포항시 남구 대송면홍계길19 (대송면사무소 2층옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "3공단", address:"경북 포항시 남구 대송면 옥명리526(3공단 배수지)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "성건동", address:"경북 경주시 성건동667-3(성건동주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "신음동", address:"경북 김천시 신음동1284 (김천시청 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "남문동", address:"경북 안동시 남문동189-5 (안동초등학교 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "공단동", address:"경북 구미시 공단동256-18 (근로자종합복지회)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "원평동", address:"경북 구미시 원평동56-4(구미중앙로 24)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "형곡동", address:"경북 구미시 형곡동142(구미시립도서관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "4공단", address:"경북 구미시 산동면봉산리 567(첨단기업1로 17)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "휴천동", address:"경북 영주시 휴천2동318-4 (휴천2동주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "중방동", address:"경북 경산시 중방동 708-5남매로 158 경산시보건소 정신보건센터 2층", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "지품면", address:"경북 영덕군 지품면 신안리산 6-2", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "화북면", address:"경북 영천시 화북면자천리 387-1번지(화북정수장내)", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "안계면", address:"경북 의성군 안계면위앙리 111번지(안계정수장내)", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "태하리", address:"경북 울릉군 서면 태하리산99-3 (울릉군 항로표지관리소)", items:"SO2, CO, O3, NO2, PM10", type:"국가배경농도"),
            Station(name: "읍내동", address:"대전 대덕구 읍내동450-11(태아산업(주))", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "문평동", address:"대전 대덕구 문평동79-1(소방파출소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "문창동", address:"대전 중구 문창동116-15 문창동 주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "구성동", address:"대전 유성구 구성동21-1(보건환경연구원)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "노은동", address:"대전 유성구 노은동  546번지노은1동 주민센터 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "대흥동1", address:"대전 중구 대흥동630-1번지 선 도로부지", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "성남동1", address:"대전 동구 성남동8-2(성남 2동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "정림동", address:"대전 서구 정림동636(정림동 주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "둔산동", address:"대전 서구 둔산동1304번지 근로자 종합복지회관(3층 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "월평동", address:"대전 서구 월평동1528번지 도로부지(월평자동차종합시장앞)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "송정동(봉명동)", address:"충북 청주시 흥덕구 송정동140-50(충북문화재연구원 옥상)(직지대로 393)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "사천동", address:"충북 청주시 상당구 사천동233-223번지(사뜸로 61번길 88-14), 청주청원도서관 옥상(2층)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "문화동", address:"충북 청주시 상당구 문화동89번지(상당로 92), 충북도청 동관 4층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "용암동", address:"충북 청주시 상당구 용암동1590(중흥로 29), 용암1동 주민센터 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "복대동", address:"충북 청주시 흥덕구 복대동111 산단육거리 교차점광장", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "성황동", address:"충남 천안시 성황동35-13 문성시립보육시설 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "백석동", address:"충남 천안시 백석동555-57번지(백성농공단지)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "성성동", address:"충남 천안시 성성동1-23번지", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "사곡면", address:"충남 공주시 사곡면 마곡사로293-106(사곡중학교)", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "독곶리", address:"충남 서산시 대산읍 독곶리123-20(농협지소)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동문동", address:"충남 서산시 동문동918-3(서산초등학교)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "난지도리", address:"충남 당진시 석문면 난지도리533", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "정곡리", address:"충남 당진시 송악면 정곡리66-12번지 정곡마을회관2층옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "모종동", address:"충남 아산시 모종동573-2 보건소옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "파도리", address:"충남 태안군 소원면 파도길51-19", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "중앙동(원주)", address:"강원 원주시 학성동206-6(중앙2동주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "명륜동", address:"강원 원주시 명륜동242-2(원주지방환경청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "옥천동", address:"강원 강릉시 옥천동327-2(옥천동주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "천곡동", address:"강원 동해시 천곡동806 (동해시청 4층 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "남양동1", address:"강원 삼척시 남양동339-1 (남양동 주민센터 3층 옥상)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "북평면", address:"강원 정선군 북평면 남평리412-1번지", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "간성읍", address:"강원 고성군 간성읍흘리 산 1-92(동원농산내 야산)", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "치악산", address:"강원 횡성군 강림면 강림리(치악산)1538번지 강림면사무소 옥상", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "호암동", address:"충북 충주시 호암동562(충주시 청소년수련원 옥상)(중원대로 3324)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "칠금동", address:"충북 충주시 칠금동874번지(칠금동 주민센터 옥상)(칠금 중랑로 37)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "장락동", address:"충북 제천시 장락동672-8(내제로 318),(시립도서관 주차장 옆, 화단)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "오창읍", address:"충북 청주시 청원구 오창읍 각리637-4 각리중학교 4층(오창중앙로 48)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "매포읍", address:"충북 단양군 매포읍 평동리1274(평동33길 3),(매포 보건지소 마당)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "청천면", address:"충북 괴산군 청천면 송문로 덕평길54-13(덕평민원봉사실)", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "삼천동", address:"전북 전주시 완산구 삼천동 2가182-1 삼천도서관 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "팔복동", address:"전북 전주시 덕진구 팔복동3가404번지 청소년자유센터 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "금암동", address:"전북 전주시 덕진구 금암동796", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "신풍동2", address:"전북 군산시 신풍동13-1 신풍동주민센터 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "소룡동", address:"전북 군산시 소룡동176-1 두산백화사무실 2층옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "개정동", address:"전북 군산시 개정동507-24 개정동주민센터 2층옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "남중동", address:"전북 익산시 남중동1가 60번지 (익산시청)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "팔봉동", address:"전북 익산시 팔봉동850", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "모현동", address:"전북 익산시 모현동2가  303-1익산시 청소년문화의 집 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "연지동", address:"전북 정읍시 중앙로 73(연지동 39-6)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "죽항동", address:"전북 남원시 죽항동 비석길 72죽항동주민센터 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "고창읍", address:"전북 고창군 고창읍 월곡리619번지 고창군 여성회관 2층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "운암면", address:"전북 임실군 운암면 선거리51-10", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "신흥", address:"인천 중구 신흥동 2가18-4 보건환경연구원 옥상(서해대로 471)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "송림", address:"인천 동구 송림동109-2번지 동구의회 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "구월동", address:"인천 남동구 구월동1296-6 구월4동 주민센터 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "숭의", address:"인천 남구 숭의동131-1번지(독정이로 95)남구의회 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "석바위", address:"인천 남구 주안6동1587(석바위 삼거리)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "부평역", address:"인천 부평구 부평3동186-218(신촌사거리)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "부평", address:"인천 부평구 부평4동440-1(부평대로88번길 19)부평동초등학교", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "연희", address:"인천 서구 심곡동244 서구청 본관", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "검단", address:"인천 서구 마전동665(검단로502번길 15)검단출장소", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "계산", address:"인천 계양구 계산동907-4(계양산로134번길 18) 계양도서관 3층 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "고잔", address:"인천 남동구 고잔동637번지 한국산업단지관리공단 경인지역본부 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "석남", address:"인천 서구 석남동573번지(거북로 116) 석남2동 주민센터", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "송해", address:"인천 강화군 송해면솔정리 357-2(전망대로 29)  송해면사무소", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "동춘", address:"인천 연수구 동춘동923-5 연수구의회 옥상", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "운서", address:"인천 중구 운서동2709-1번지 영마루 공원 내", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "송현", address:"인천 동구 송현동119번지 송현변전소", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "논현", address:"인천 남동구 논현동논현 제2 근린공원 내", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "원당", address:"인천 서구 원당동원당지구 76B 1L 검단선사박물관", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "소사본동", address:"경기 부천시 소사구 경인옛로 72(소사구청 소향관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "내동", address:"경기 부천시 오정구 삼작로 114(신흥동주민센터)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "중2동", address:"경기 부천시 원미구 심중로 121(책마루도서관)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "오정동", address:"경기 부천시 오정구 성오로 172(오정구청아트홀)", items:"SO2, CO, O3, NO2, PM10", type:"도시대기"),
            Station(name: "계남공원", address:"경기 부천시 원미구 중4동1030-3 (계남공원 사거리)", items:"SO2, CO, O3, NO2, PM10", type:"도로변대기"),
            Station(name: "석모리", address:"인천 강화군 삼산면 석모리347-4(해병 1935부대)", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "덕적도", address:"인천 옹진군 덕적면 진리산 35-4번지", items:"SO2, CO, O3, NO2, PM10", type:"교외대기"),
            Station(name: "백령도", address:"인천 옹진군 백령면 연화리산1025-1", items:"SO2, CO, O3, NO2, PM10", type:"국가배경농도"),
            Station(name: "운정", address:"경기 파주시 야당동331-9", items:"SO2, CO, O3, NO2, PM10", type:"도시대기")
        ]
        
        //let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        //let tableViewController = mainStoryboard.instantiateViewControllerWithIdentifier("MainTableViewController") as! MainTableViewController
        if (true) {
        let navController = window!.rootViewController as! UINavigationController
        
            /*
            Note we want the first view controller (not the visibleViewController) in case
            we are being store from UIStateRestoration.
            */
            let mainViewController = navController.viewControllers.first as! TodayAirViewController
            mainViewController.stations = stations
            
            if UIScreen.mainScreen().bounds.size.height == 480 {
                // iPhone 4
                mainViewController.screenSize = mainViewController.SCREEN_IPHONE_4
            } else if UIScreen.mainScreen().bounds.size.height == 568 {
                // IPhone 5
                mainViewController.screenSize = mainViewController.SCREEN_IPHONE_5
            } else if UIScreen.mainScreen().bounds.size.width == 375 {
                // iPhone 6
                mainViewController.screenSize = mainViewController.SCREEN_IPHONE_6
            } else if UIScreen.mainScreen().bounds.size.width == 414 {
                // iPhone 6+
                mainViewController.screenSize = mainViewController.SCREEN_IPHONE_6P
            }
        }
        return true
    }
    
    func applicationWillResignActive(application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(application: UIApplication) {
        // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }


}

